title: Ahmed Ayman
logo: /assets/img/ME.jpg
description: I leverage advanced Python and machine learning techniques to extract actionable insights from complex data, empowering businesses to make informed decisions.
# show_downloads: true
theme: jekyll-theme-minimal
